name: Latest Build

on:
  push:
    branches:
      - '*'
      - '!development_old_nwjs'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        bit: [32, 64]
        nwjs: ['0.82.0', '0.44.5']
        exclude:
          - os: macOS-latest
            bit: 32

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: yarn version
        run: |
          yarn version

      - name: node version
        run: |
          node --version

      - uses: kanga333/variable-mapper@master
        with:
          key: "${{ matrix.os }}"
          map: |
            {
              "ubuntu-latest": { "platform": "linux" },
              "windows-latest": { "platform": "win" },
              "macOS-latest": { "platform": "osx" }
            }

      - name: Build info
        run: echo Build ${{ env.platform }}${{ matrix.bit }} on nw-v${{ matrix.nwjs }}

      - name: Build App
        run: |
          yarn
          yarn gulp dist --platforms=${{ env.platform }}${{ matrix.bit }} --nwVersion=${{ matrix.nwjs }}

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.platform }}${{ matrix.bit }}-${{ matrix.nwjs }}
          path: build

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Context
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get the version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R artifacts

      - uses: actions/download-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: ubuntu-latest

      - uses: actions/download-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: windows-latest

      - uses: actions/download-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: macOS-latest

      - run: find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset [macOS-zip]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macOS-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-osx64.zip
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-osx64.zip
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [macOS-pkg]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macOS-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}.pkg
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}.pkg
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [ubuntu-deb-amd64]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-amd64.deb
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-amd64.deb
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [ubuntu-zip-x64]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-linux64.zip
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-linux64.zip
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [ubuntu-deb-i386]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-i386.deb
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-i386.deb
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [ubuntu-zip-x32]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-linux32.zip
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-linux32.zip
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [windows-zip-x64]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win64.zip
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win64.zip
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [windows-zip-ia32]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win32.zip
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win32.zip
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [windows-setup-x64]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win64-Setup.exe
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win64-Setup.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [windows-setup-ia32]
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-latest/Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win32-Setup.exe
          asset_name: Popcorn-Time-${{ steps.get_version.outputs.VERSION }}-win32-Setup.exe
          asset_content_type: application/octet-stream
